#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

socket_path=$1
config=$2
postgresql_uri=$(jq -r '.["postgresql-uri"]' < $config)

exec java -jar $(dirname $0)/jsqlon.jar --socket $socket_path $postgresql_uri
