#!/bin/sh

check() {
  command -v "$1" >/dev/null || {
    echo "Could not find \"$1\". Please install ${2:-it}." >&2
    exit 1
  }
}

check go 'Go'
check http 'HTTPie'
check ruby 'Ruby'
check rustc 'Rust'
check zsh
check jq
check dos2unix
