#!/bin/sh

check() {
  command -v "$1" >/dev/null || {
    echo "Could not find \"$1\". Please install ${2:-it}." >&2
    exit 1
  }
}

check http 'HTTPie'
check node 'node.js'
check ruby 'Ruby'
check zsh
